# Generated by Django 5.1.6 on 2025-03-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('anno_edizione', models.IntegerField(blank=True, null=True)),
                ('autori', models.ManyToManyField(to='gestione_biblioteca.autore')),
                ('editore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_biblioteca.editore')),
            ],
        ),
    ]
